//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ServiceReferenceRecetaAlumno {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRecetaAlumno.IServiceRecetaAlumno")]
    public interface IServiceRecetaAlumno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecetaAlumno/GetAll", ReplyAction="http://tempuri.org/IServiceRecetaAlumno/GetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.RecetaAlumno))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Alumno))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Receta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        ML.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecetaAlumno/GetAll", ReplyAction="http://tempuri.org/IServiceRecetaAlumno/GetAllResponse")]
        System.Threading.Tasks.Task<ML.Result> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecetaAlumno/Add", ReplyAction="http://tempuri.org/IServiceRecetaAlumno/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Receta))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Alumno))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.RecetaAlumno))]
        ML.Result Add(ML.RecetaAlumno recetaAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecetaAlumno/Add", ReplyAction="http://tempuri.org/IServiceRecetaAlumno/AddResponse")]
        System.Threading.Tasks.Task<ML.Result> AddAsync(ML.RecetaAlumno recetaAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecetaAlumno/Update", ReplyAction="http://tempuri.org/IServiceRecetaAlumno/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.RecetaAlumno))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Alumno))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Receta))]
        ML.Result Update(ML.Receta receta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRecetaAlumno/Update", ReplyAction="http://tempuri.org/IServiceRecetaAlumno/UpdateResponse")]
        System.Threading.Tasks.Task<ML.Result> UpdateAsync(ML.Receta receta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRecetaAlumnoChannel : PL.ServiceReferenceRecetaAlumno.IServiceRecetaAlumno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRecetaAlumnoClient : System.ServiceModel.ClientBase<PL.ServiceReferenceRecetaAlumno.IServiceRecetaAlumno>, PL.ServiceReferenceRecetaAlumno.IServiceRecetaAlumno {
        
        public ServiceRecetaAlumnoClient() {
        }
        
        public ServiceRecetaAlumnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRecetaAlumnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRecetaAlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRecetaAlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ML.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ML.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ML.Result Add(ML.RecetaAlumno recetaAlumno) {
            return base.Channel.Add(recetaAlumno);
        }
        
        public System.Threading.Tasks.Task<ML.Result> AddAsync(ML.RecetaAlumno recetaAlumno) {
            return base.Channel.AddAsync(recetaAlumno);
        }
        
        public ML.Result Update(ML.Receta receta) {
            return base.Channel.Update(receta);
        }
        
        public System.Threading.Tasks.Task<ML.Result> UpdateAsync(ML.Receta receta) {
            return base.Channel.UpdateAsync(receta);
        }
    }
}
