//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecetasAlumno
    {
        public int IdRecetasAlumnos { get; set; }
        public Nullable<int> IdReceta { get; set; }
        public Nullable<int> Matricula { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Receta Receta { get; set; }
    }
}
